### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by adheep** [adriaciurana/DragGAN#5]
Getting this error when trying to run 'python gradio_app.py'

Traceback (most recent call last):
  File "gradio_app.py", line 11, in <module>
    from drag_gan.drag_gan import DragGAN
  File "D:\Projects\Python\DragGAN\drag_gan\drag_gan.py", line 77, in <module>
    class DragGAN:
  File "D:\Projects\Python\DragGAN\drag_gan\drag_gan.py", line 93, in DragGAN
    def params(self) -> dict[str, Any]:
TypeError: 'type' object is not subscriptable

any idea how you can fix it?

**Comment by adriaciurana** [comment]
I think that maybe is the python version. If I remember correct, previous version than 3.7 needs `typing.Dict` in contrast to `dict`. Which python version are you using?

**Comment by adheep** [comment]
I am using `Python 3.8.6` version

**Comment by adriaciurana** [comment]
Sorry, the problem is not that it is 3.6.

Starting with 3.6, typing was introduced, but it wasn't until 3.9 that typing.Dict was replaced by dict. I'm using 3.9.

There are several ways to fix the problem:
- The simplest is to update your environment to 3.9.
- Add `from __future__ import annotations` to the first line of the file.
- Import `typing.Dict` and replace `dict` with `Dict`.

**Comment by xunshengliuyin** [comment]
from typing import Dict , Any,List， Not only dict
